apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubeinvaders-programming-mode
  namespace: kubeinvaders
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - watch
      - delete

  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubeinvaders-programming-mode
  namespace: kubeinvaders
subjects:
  - kind: ServiceAccount
    name: kinv-sa
    namespace: kubeinvaders
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeinvaders-programming-mode